# Generated by Django 4.2.2 on 2023-06-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_teammem',
        ),
    ]
