# Generated by Django 4.2.2 on 2023-06-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_delete_tb_teammem'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_teammem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=150)),
                ('designtn', models.CharField(max_length=250)),
            ],
        ),
    ]
